// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:holefeeder/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AccountAdapter());
    registerAdapter(AccountInfoAdapter());
    registerAdapter(AccountTypeAdapter());
    registerAdapter(CategoryAdapter());
    registerAdapter(CategoryInfoAdapter());
    registerAdapter(CategoryTypeAdapter());
    registerAdapter(DateIntervalTypeAdapter());
    registerAdapter(TagAdapter());
    registerAdapter(TransactionAdapter());
    registerAdapter(UpcomingAdapter());
    registerAdapter(UserSettingsAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AccountAdapter());
    registerAdapter(AccountInfoAdapter());
    registerAdapter(AccountTypeAdapter());
    registerAdapter(CategoryAdapter());
    registerAdapter(CategoryInfoAdapter());
    registerAdapter(CategoryTypeAdapter());
    registerAdapter(DateIntervalTypeAdapter());
    registerAdapter(TagAdapter());
    registerAdapter(TransactionAdapter());
    registerAdapter(UpcomingAdapter());
    registerAdapter(UserSettingsAdapter());
  }
}
