# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: ["main"]
    paths:
      - "holefeeder-flutter/**"
      - ".github/workflows/cicd.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "holefeeder-flutter/**"
      - ".github/workflows/cicd.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./holefeeder-flutter

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: flutter format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze
        working-directory: ./holefeeder-flutter

      - name: Run tests
        run: flutter test
        working-directory: ./holefeeder-flutter
